package com.databridge.mybridge.domain.model.login

import com.google.gson.annotations.SerializedName

class UserInfo(
    @SerializedName("id") var id: Int? = null,
    @SerializedName("user_uuid") var userUuid: String? = null,
    @SerializedName("slug") var slug: String? = null,
    @SerializedName("first_name") var firstName: String? = null,
    @SerializedName("last_name") var lastName: String? = null,
    @SerializedName("email") var email: String? = null,
    @SerializedName("profile_headline") var profileHeadline: String? = null,
    @SerializedName("profile_intro") var profileIntro: String? = null,
    @SerializedName("mobile_number") var mobileNumber: String? = null,
    @SerializedName("former_name") var formerName: String? = null,
    @SerializedName("profile_mobile_number") var profileMobileNumber: String? = null,
    @SerializedName("is_mobile_verified") var isMobileVerified: Boolean? = null,
    @SerializedName("is_visible") var isVisible: Boolean? = null,
    @SerializedName("is_active") var isActive: Boolean? = null,
    @SerializedName("is_email_verified") var isEmailVerified: Boolean? = null,
    @SerializedName("is_onboarding_completed") var isOnboardingCompleted: Boolean? = null,
    @SerializedName("profile_pic") var profilePic: String? = null,
    @SerializedName("profile_banner_pic") var profileBannerPic: String? = null,
    @SerializedName("public_profile_url") var publicProfileUrl: String? = null,
    @SerializedName("dob") var dob: String? = null,
    @SerializedName("interested_in") var interestedIn: String? = null,
    @SerializedName("causes_you_care") var causesYouCare: String? = null,
    @SerializedName("follow_count") var followCount: String? = null,
    @SerializedName("connect_count") var connectCount: String? = null,
    @SerializedName("skills") var skills: String? = null,
    @SerializedName("position") var position: String? = null,
    @SerializedName("location") var location: String? = null,
    @SerializedName("lang") var lang: String? = null,
    @SerializedName("is_staff") var isStaff: Boolean? = null,
    @SerializedName("profile_email") var profileEmail: String? = null,
    @SerializedName("google_calendar_email") var googleCalendarEmail: String? = null,
    @SerializedName("outlook_calendar_email") var outlookCalendarEmail: String? = null,
    @SerializedName("country") var country: String? = null,
    @SerializedName("state") var state: String? = null,
    @SerializedName("city") var city: String? = null,
    @SerializedName("experience") var experience: Experience? = Experience(),
    @SerializedName("education") var education: Education? = Education(),
    @SerializedName("eligibility") var eligibility: Boolean? = null,
    @SerializedName("is_student") var isStudent: Boolean? = null,
    @SerializedName("fcm_token") var fcmToken: String? = null,
    @SerializedName("matrix_user_id") var matrixUserId: String? = null,
    @SerializedName("language") var language: ArrayList<String> = arrayListOf(),
    @SerializedName("matrix_status") var matrixStatus: String? = null,
    @SerializedName("matrix_presence") var matrixPresence: String? = null,
    @SerializedName("display_name") var displayName: String? = null,
    @SerializedName("lang_name") var langName: String? = null,
    @SerializedName("role") var role: String? = null,
    @SerializedName("has_premium_subscription") var hasPremiumSubscription: Boolean? = null,
    @SerializedName("language_list") var languageList: ArrayList<String> = arrayListOf(),
    @SerializedName("contacts_synced") var contactsSynced: Boolean? = null,
    @SerializedName("profile_pic_chars") var profilePicChars: String? = null,

//    @SerializedName("field_audience") var fieldAudience: FieldAudience? = FieldAudience(),
    @SerializedName("website") var website: String? = null,
    @SerializedName("social_links") var socialLinks: ArrayList<String> = arrayListOf(),
    @SerializedName("gender") var gender: String? = null,
    @SerializedName("pronouns") var pronouns: String? = null,
    @SerializedName("date_of_birth") var dateOfBirth: String? = null

)